import { AnalysisResult } from "@/types";

/**
 * Generate a comprehensive Markdown report from an ATLAS AnalysisResult object.
 */
export function generateMarkdownReport(result: AnalysisResult): string {
  const { data, repoFullName, commitSha, primaryLanguage, starsCount, filesAnalyzedCount, repoUrl } = result;
  const { architectureSummary, codeExplanations, onboardingGuide, healthScorecard } = data;

  const dateStr = new Date(result.createdAt || Date.now()).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  let md = `# 🗺 Architecture Analysis Report: ${repoFullName}

> **Generated by ATLAS (AI Repository Explainer)** on ${dateStr}  
> **Repository:** [${repoUrl}](${repoUrl}) | **Commit SHA:** \`${commitSha.slice(0, 7)}\` | **Stars:** ⭐ ${starsCount.toLocaleString()} | **Language:** ${primaryLanguage ?? "Polyglot"}

---

## 📋 Executive Architecture Overview

${architectureSummary.overview}

- **Project Type:** ${architectureSummary.projectType}
- **Primary Tech Stack:** ${architectureSummary.techStack.join(", ")}
- **Core Architecture Concepts:**
${architectureSummary.coreConcepts.map((c) => `  - ${c}`).join("\n")}

---

## 🗺 System Architecture Diagram

\`\`\`mermaid
${data.mermaidDiagram}
\`\`\`

---

## 📂 Codebase Breakdown & Module Explanations

${codeExplanations.modules
  .map(
    (mod) => `### 📁 ${mod.name} (\`${mod.path}\`)

**Description:** ${mod.description}  
**Purpose:** ${mod.purpose}

#### Key Files in Module:
${mod.files
  .map(
    (f) => `- [\`${f.path}\`](${f.githubUrl}) — ${f.purpose}${
      f.keyExports?.length ? ` (Exports: \`${f.keyExports.join("`, `")}\`)` : ""
    }`
  )
  .join("\n")}
`
  )
  .join("\n---\n\n")}

---

## 🚀 Onboarding Guide & Local Setup

### Runtime Requirements
${onboardingGuide.runtimeRequirements.map((r) => `- ${r}`).join("\n")}

### Quick Start Commands
\`\`\`bash
${onboardingGuide.setupSteps.map((s) => `# ${s.description}\n${s.command}`).join("\n\n")}
\`\`\`

### Recommended Reading Path
${onboardingGuide.startReadingPath.map((p, i) => `${i + 1}. \`${p}\``).join("\n")}

### Key Development Conventions
${onboardingGuide.keyConventions.map((c) => `- ${c}`).join("\n")}

### Good First Areas to Explore
${onboardingGuide.goodFirstAreas.map((a) => `- \`${a}\``).join("\n")}
`;

  if (healthScorecard) {
    md += `\n---\n\n## 🛡 Codebase Health & Security Scorecard\n\n`;
    md += `**Overall Grade:** **${healthScorecard.overallGrade}** (${healthScorecard.overallScore}/100)\n\n`;
    md += `### Category Ratings\n`;
    healthScorecard.metrics.forEach((m) => {
      md += `- **${m.category}:** Grade **${m.grade}** (${m.score}/100)\n  - *Summary:* ${m.summary}\n  - *Recommendation:* ${m.recommendation}\n`;
    });
  }

  md += `\n---\n*Report generated automatically by [ATLAS](https://github.com/Giancyril/Atlas) with Google Gemini AI. ${filesAnalyzedCount} files analyzed.*`;

  return md;
}

/** Generate HTML markdown badge for embedding in GitHub READMEs */
export function generateReadmeBadge(repoFullName: string): string {
  const encodedRepo = encodeURIComponent(repoFullName);
  return `[![Analyzed with ATLAS](https://img.shields.io/badge/Architecture-Analyzed%20with%20ATLAS-4f8ef7?style=for-the-badge&logo=github)](https://github.com/Giancyril/Atlas)`;
}
